# Generated by Django 4.0.3 on 2022-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='services',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='services',
            name='rating',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
