# Generated by Django 4.0.3 on 2022-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0002_alter_services_latitude_alter_services_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sliding_scale',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
