# Generated by Django 4.0.3 on 2022-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0003_services_sliding_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='sliding_scale',
            field=models.BooleanField(default=True),
        ),
    ]
