# Generated by Django 4.0.3 on 2022-03-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0004_services_online_alter_services_sliding_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
