# Generated by Django 4.0.3 on 2022-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0005_event_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
