# Generated by Django 4.0.3 on 2022-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuminateapi', '0006_remove_post_title_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_img',
            field=models.FileField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
